name: Scrape json Data

on:
  push:
    branches-ignore: ["data"]
    paths-ignore:
      - '**.json'
  schedule: # Ref https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 */2 * * *' # Ref https://crontab.guru/examples.html

env:
  PATHWAY_SAVE: roi/
  TIMEZONE: Europe/Moscow

jobs:
  changed_files:
    name: Check if scrape is needed
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should_scrape: ${{ steps.decide.outputs.should_scrape }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.ref }}

      - name: Decide if scrape is needed
        id: decide
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "Triggered by schedule. Scraping..."
            echo "should_scrape=true" >> $GITHUB_OUTPUT
          else
            BEFORE_SHA="${{ github.event.before }}"
            CURRENT_SHA="${{ github.sha }}"
            
            if [ "$BEFORE_SHA" == "0000000000000000000000000000000000000000" ]; then
              echo "First commit. Scraping..."
              echo "should_scrape=true" >> $GITHUB_OUTPUT
            else
               CHANGED_NON_JSON=$(git diff --name-only ${BEFORE_SHA} ${CURRENT_SHA} | grep -v '\.json$' | xargs)
              if [ -n "$CHANGED_NON_JSON" ]; then
                echo "Non-JSON files changed: $CHANGED_NON_JSON"
                echo "should_scrape=true" >> $GITHUB_OUTPUT
              else
                echo "Only JSON or no files changed. Skipping scrape."
                echo "should_scrape=false" >> $GITHUB_OUTPUT
              fi
            fi
          fi

  deploy_and_scrape:
    name: Scrape and Push to 'data' branch
    runs-on: ubuntu-latest
    needs: changed_files
    if: needs.changed_files.outputs.should_scrape == 'true'
    permissions: # Ref https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write
    steps:
      - name: Checkout 'master' branch (for scripts)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Switch to 'data' branch & sync
        run: |
          DATA_BRANCH="data"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
          # Check if 'data' branch exists
          if git show-ref --verify --quiet refs/remotes/origin/$DATA_BRANCH; then
            echo "Branch '$DATA_BRANCH' exists. Checking out..."
            git checkout -b $DATA_BRANCH origin/$DATA_BRANCH
            git pull origin $DATA_BRANCH --no-rebase
          else
            echo "Branch '$DATA_BRANCH' does not exist. Creating orphan branch..."
            git checkout --orphan $DATA_BRANCH
            # Clear the 'staging area', since 'orphan branch' inherits files from 'master'
            git rm -rf .
          fi

      - name: Install dependencies
        run: npm install

      - name: Run scrape script
        run: npm run update-roi
        env:
          PATHWAY_SAVE: ${{ env.PATHWAY_SAVE }}
          TIMEZONE: ${{ env.TIMEZONE }}

      - name: Commit and Push changes to 'data'
        run: |
          DATA_BRANCH="data"
          git add .
          
          # Checking for changes
          if git diff --staged --quiet; then
            echo "No changes in '${{ env.PATHWAY_SAVE }}' folder to commit. Skipping push."
            exit 0
          fi
          
          git commit -m "Auto-update json files [skip ci]: ${{ github.sha }}"
          git push origin $DATA_BRANCH --force-with-lease || git push origin $DATA_BRANCH
          echo "Successfully pushed updates to '$DATA_BRANCH' branch."
