name: Scrape json Data

on:
  push:
    paths-ignore:
    - '**'
  schedule:
    - cron: '0 * * * *' # Ref https://crontab.guru/examples.html
  
env:
  BRANCH_NAME: 'master'
  TIMEZONE: 'Europe/Moscow' # Optional
  
jobs:
  deploy_and_scrape:
    name: Scrape
    permissions:
      contents: write # Ref https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Run scrape script
      run: npm run update-roi
      env:
        PATHWAY_SAVE: '/data/roi'
    - uses: corcc/publish@master
      env:
        TASK_NAME: 'Data query:'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
